name: .NET

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install SonarCloud scanner
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Restore dependencies
      run: dotnet restore SimpleCalculatorSolution.sln
    
    - name: Run SonarCloud analysis
      run: dotnet sonarscanner begin /k:"EvgenyYushko_gpt-SimpleCalculatorSolution" /o:"evgenyyushko" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

    - name: Build solution
      run: dotnet build SimpleCalculatorSolution.sln --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test SimpleCalculator.Tests/SimpleCalculator.Tests.csproj --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"

    - name: End SonarCloud analysis
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

    - name: Publish test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: '**/TestResults/*.trx'

    # Шаг для отправки уведомления в Telegram при успешном билде
    - name: Send success message to Telegram
      if: success()
      run: |
        curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
        -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
        -d "text=✅ Build and tests passed successfully for ${{ github.repository }} on branch ${{ github.ref }}"

  # Шаг для отправки уведомления в Telegram при ошибке
    - name: Send failure message to Telegram
      if: failure()
      run: |
        curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
        -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
        -d "text=❌ Build or tests failed for ${{ github.repository }} on branch ${{ github.ref }}"