name: Build and deploy ASP.Net Core app to Azure Web App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Restore dependencies
      run: dotnet restore SimpleCalculatorSolution.sln

    - name: Build solution
      run: dotnet build SimpleCalculatorSolution.sln --configuration Release --no-restore

    - name: Publish artifact
      run: dotnet publish SimpleCalculatorApi/SimpleCalculatorApi.csproj --configuration Release --output ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: <YOUR_APP_SERVICE_NAME>
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish